import type { Metadata } from 'next'
import { Inter, League_Spartan } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const league = League_Spartan({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${league.className} bg-black text-zinc-100 `}>{children}</body>
    </html>
  )
}
